using System.Text;

namespace Anchor.Services;

public class AutounattendOptions
{
    public string UserName { get; set; } = "User";
    public string ComputerName { get; set; } = "ANCHOR-PC";
    public string Locale { get; set; } = "en-US";
    public string TimeZone { get; set; } = "UTC";
    public bool SkipPrivacyQuestions { get; set; } = true;
    public bool DisableTelemetry { get; set; } = true;
    public bool BypassHardwareChecks { get; set; }
    public bool LocalAccountOnly { get; set; } = true;
}

/// <summary>Generates an Autounattend.xml so power users can replicate an Anchor-tuned
/// Windows setup across multiple PCs. Place the file on the root of install media.</summary>
public static class AutounattendService
{
    public static string Generate(AutounattendOptions o)
    {
        var firstLogon = new StringBuilder();
        int order = 1;
        void Cmd(string c) => firstLogon.Append($@"
                <SynchronousCommand wcm:action=""add"">
                    <Order>{order++}</Order>
                    <CommandLine>{System.Security.SecurityElement.Escape(c)}</CommandLine>
                </SynchronousCommand>");

        if (o.DisableTelemetry)
            Cmd(@"reg add HKLM\SOFTWARE\Policies\Microsoft\Windows\DataCollection /v AllowTelemetry /t REG_DWORD /d 0 /f");
        if (o.LocalAccountOnly)
            Cmd(@"reg add HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\OOBE /v BypassNRO /t REG_DWORD /d 1 /f");

        string bypass = "";
        if (o.BypassHardwareChecks)
            bypass = @"
            <component name=""Microsoft-Windows-Setup"" processorArchitecture=""amd64"" publicKeyToken=""31bf3856ad364e35"" language=""neutral"" versionScope=""nonSxS"">
                <RunSynchronous>
                    <RunSynchronousCommand wcm:action=""add"">
                        <Order>1</Order>
                        <Path>reg add HKLM\SYSTEM\Setup\LabConfig /v BypassTPMCheck /t REG_DWORD /d 1 /f</Path>
                    </RunSynchronousCommand>
                    <RunSynchronousCommand wcm:action=""add"">
                        <Order>2</Order>
                        <Path>reg add HKLM\SYSTEM\Setup\LabConfig /v BypassSecureBootCheck /t REG_DWORD /d 1 /f</Path>
                    </RunSynchronousCommand>
                    <RunSynchronousCommand wcm:action=""add"">
                        <Order>3</Order>
                        <Path>reg add HKLM\SYSTEM\Setup\LabConfig /v BypassRAMCheck /t REG_DWORD /d 1 /f</Path>
                    </RunSynchronousCommand>
                </RunSynchronous>
            </component>";

        return $@"<?xml version=""1.0"" encoding=""utf-8""?>
<!-- Generated by Anchor (open-source). Review before use: this file automates Windows Setup. -->
<unattend xmlns=""urn:schemas-microsoft-com:unattend"" xmlns:wcm=""http://schemas.microsoft.com/WMIConfig/2002/State"">
    <settings pass=""windowsPE"">
        <component name=""Microsoft-Windows-International-Core-WinPE"" processorArchitecture=""amd64"" publicKeyToken=""31bf3856ad364e35"" language=""neutral"" versionScope=""nonSxS"">
            <SetupUILanguage><UILanguage>{o.Locale}</UILanguage></SetupUILanguage>
            <InputLocale>{o.Locale}</InputLocale>
            <SystemLocale>{o.Locale}</SystemLocale>
            <UILanguage>{o.Locale}</UILanguage>
            <UserLocale>{o.Locale}</UserLocale>
        </component>{bypass}
    </settings>
    <settings pass=""specialize"">
        <component name=""Microsoft-Windows-Shell-Setup"" processorArchitecture=""amd64"" publicKeyToken=""31bf3856ad364e35"" language=""neutral"" versionScope=""nonSxS"">
            <ComputerName>{o.ComputerName}</ComputerName>
            <TimeZone>{o.TimeZone}</TimeZone>
        </component>
    </settings>
    <settings pass=""oobeSystem"">
        <component name=""Microsoft-Windows-Shell-Setup"" processorArchitecture=""amd64"" publicKeyToken=""31bf3856ad364e35"" language=""neutral"" versionScope=""nonSxS"">
            <OOBE>
                <HideEULAPage>true</HideEULAPage>
                <HideWirelessSetupInOOBE>false</HideWirelessSetupInOOBE>
                <ProtectYourPC>{(o.SkipPrivacyQuestions ? 3 : 1)}</ProtectYourPC>
                <HideOnlineAccountScreens>{o.LocalAccountOnly.ToString().ToLower()}</HideOnlineAccountScreens>
            </OOBE>
            <UserAccounts>
                <LocalAccounts>
                    <LocalAccount wcm:action=""add"">
                        <Name>{o.UserName}</Name>
                        <Group>Administrators</Group>
                        <DisplayName>{o.UserName}</DisplayName>
                    </LocalAccount>
                </LocalAccounts>
            </UserAccounts>
            <FirstLogonCommands>{firstLogon}
            </FirstLogonCommands>
        </component>
    </settings>
</unattend>";
    }

    /// <summary>Saves to Documents\Anchor\Autounattend.xml and returns the path.</summary>
    public static string Save(AutounattendOptions o)
    {
        var dir = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments), "Anchor");
        Directory.CreateDirectory(dir);
        var path = Path.Combine(dir, "Autounattend.xml");
        File.WriteAllText(path, Generate(o));
        return path;
    }
}
